version: '3'
services:
  movie-mysql:
    image: mysql:latest
    network_mode: host
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moviedb
      MYSQL_USER_NAME: root
      MYSQL_PASSWORD: root
  userapp:
    image: user-app
    build: movie-cruiser-authentication/
    restart: always
    network_mode: host
    container_name: userapp-docker
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
    - movie-mysql
  movieapp:
    image: movie-app
    build: backend/
    restart: always
    network_mode: host
    container_name: moviespring-docker
    ports:
      - 8082:8082
    expose:
      - 8082
    depends_on:
    - movie-mysql
  angular:
    image: angular-image
    build: forntend/
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
    expose:
      - 4200
